[package]
name = "client"
version = "0.1.0"
authors = ["Christofer Nolander <christofer.nolander@gmail.com>"]

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
reqwest = "0.9.2"
ring = "0.11.0"

file_hash = { path = "../file_hash" }